### ISSUE TITLE
Regarding the other lib - typescript-native

### ISSUE THREAD

**Issue by klesun** [klesun/ts-browser#1]
### Regarding [typescript-native](https://github.com/Hashbrown777/typescript-native/blob/master/react.html)

Answering questions @Hashbrown777 here to not flood in [SO comments](https://stackoverflow.com/a/23076788/2750743).

* Q: Is yours able to have typescript embedded in the html as you would js too
    A: Nope, current API expects all ts files to be in a separate file. Though I  guess it won't be hard to add another function like `compileTsScriptTags()` besides the `loadModule(url)` at some point.

* Q: but how do you handle lib imports like lib.dom.d.ts
    A: `.d.ts` would result in empty files, as ts transpiler just cuts types off. Though there will be declarations of imported `d.ts` module, since my dependency resolver can not distinct between type import and value import... Regarding `node_modules` my implementation expects you to specify full path to a file in `node_modules` like
    ```typescript
    import momentjs from '../../node_modules/momentjs/lib/momentjs.min.js';` 
    ```
    (given that your `node_modules` is publicly available, not sure, how much of a good practice is it)

Dunno, maybe we could merge two good libs into one very good lib? =-D

**Comment by klesun** [comment]
P.S. I'm not checking types during compilation, since I believe it's much slower this way, so there is no need to load `.d.ts` files - I'm just calling `window.ts.transpile(src)` from `typescriptServices.js` like @basarat did.
(supposing all type checks were already done in IDE during development)

**Comment by Hashbrown777** [comment]
Ah, okay. I did it by abusing `@type` and I used `@id` to give "filenames" to inline `script[type$=typescript]` tags.
All compile from string (even url resources, which are just `fetch(script.src)`d, ordinarily `script.text`'d) in my implementation, I think I was afraid of encountering CORS.
It's still pretty quick, compilation time is `console.log()`d, but my demo is very small (the demo is also slow to load though, because I pull all the ts resources from github-raw instead of including them "locally", it was a midnight hack!).

I havent tried `import x from <url>;` (all imports correspond to an `@id`), so it's less web-modules and more "pretending to be a local compiler".
Kinda like if you downloaded all the `.d.ts` files on your local filesystem, but it means even external resources need the `@id` (just like local files would need a local filepath).  

When I get around to actually using it (it was built for a purpose, I swear) I might try to use yours instead and retrofit in my extra functionality.
Like I mentioned in that SO post, I didn't even attempt proper circular dependencies at all!
Thanks for the response!

**Comment by Hashbrown777** [comment]
I notice you `data:text/javascript;base64,`-encode, and that is so cheeky (mine outputs the js to `<script>` tags so you can inspect them), but it might allow you to compile to es6 with that!
Have you tried? I saw that it's compiling to es5 for both target and module type.

This doesn't seem configurable which I think needs to be added.
typescript-native allows users of `runTS()` (equivalent of your `loadModule()`) to add their own options (like `jsx : ts.JsxEmit.React`) which I think people would need (please let me know if I'm blind and it's configured elsewhere).

With the url encoding way of doing it, would it have any impact as individual ts files get larger &/or projects with lots of inter-depependcies?

**Comment by klesun** [comment]
Yeah, most likely it should be made configurable. I was like "if it runs on last chrome then it's ok" at the moment of writing =-D. I'll [add the ability](https://github.com/klesun/ts-browser/issues/2) to pass options to compiller today or this weekend.

The encoding does make files 33% or something larger, though much relevant problem for scaling is that each file compiles 10-50 ms. So for 10 files it's 500 ms, for 100 files it's 5000 ms. I wonder if there are any solutions...

**Comment by klesun-misc** [comment]
[Added ability](https://github.com/klesun/ts-browser/issues/2) to configure it:
https://github.com/klesun-misc/ts-browser-react-example
https://klesun-misc.github.io/ts-browser-react-example/

Will think how to deal with CommonJS modules out of the box later.

**Comment by klesun** [comment]
About CommonJS, I managed to [scrap something](https://github.com/klesun-misc/ts-browser-react-example/blob/master/cjstoes6/react.es6.js). It is not as seemless as with webpack, but still much better than listing all dependencies in html separately from js code that uses them.

There is also this convenient way to use it, but it should be used cautiously:
```javascript
import {$} from 'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js';
```
In addition to the `window.someLib` the imported module will also return a value - an object with all new keys that were added to the `window.` during it's evaluation + `.default` field holding the main added field, if the lib adds just one key to the `window.`. So you can also use it like this:
```javascript
import customJqueryVarName from 'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js';
```
But note that these two methods are dangerous in the way, that if you already included the lib by some other means (like `<script>` tag), returned value will be `undefined` and you'll only be able to use it like this:
```javascript
import 'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js';
const $ = window.$;
```
